/*
 * Copyright (c) 2017-2021 DarkCompet. All rights reserved.
 */

package tool.compet.core.animation;

public enum DkInterpolatorType {
	LINEAR, // line

	// See ease types at: https://easings.net
	EASE_BACK_IN,
	EASE_BACK_OUT,
	EASE_BACK_IN_OUT,
	EASE_BOUNCE_IN,
	EASE_BOUNCE_OUT,
	EASE_BOUNCE_IN_OUT,
	EASE_CIRC_IN,
	EASE_CIRC_OUT,
	EASE_CIRC_IN_OUT,
	EASE_CUBIC_IN,
	EASE_CUBIC_OUT,
	EASE_CUBIC_IN_OUT,
	EASE_ELASTIC_IN, // elastic
	EASE_ELASTIC_OUT,
	EASE_ELASTIC_IN_OUT,
	EASE_EASE_IN_EXPO,
	EASE_EASE_OUT_EXPO,
	EASE_EASE_IN_OUT_EXPO,
	EASE_QUAD_IN,
	EASE_QUAD_OUT,
	EASE_QUAD_IN_OUT,
	EASE_QUART_IN,
	EASE_QUART_OUT,
	EASE_QUART_IN_OUT,
	EASE_QUINT_IN,
	EASE_QUINT_OUT,
	EASE_QUINT_IN_OUT,
	EASE_SINE_IN,
	EASE_SINE_OUT,
	EASE_SINE_IN_OUT,
}
